/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(Auth)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(Auth)'}/Signup` | `/Signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(SeparatePages)'}/MasterPassword` | `/MasterPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(SeparatePages)'}/UpdatePass` | `/UpdatePass`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(SeparatePages)'}/Password` | `/Password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(tabs)'}/Vault` | `/Vault`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Pages)'}${'/(Auth)'}/Login` | `/Login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Pages)'}${'/(Auth)'}/Signup` | `/Signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Pages)'}${'/(SeparatePages)'}/MasterPassword` | `/MasterPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Pages)'}${'/(SeparatePages)'}/UpdatePass` | `/UpdatePass`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Pages)'}${'/(SeparatePages)'}/Password` | `/Password`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Pages)'}${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Pages)'}${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(Pages)'}${'/(tabs)'}/Vault` | `/Vault`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(Pages)'}${'/(Auth)'}/Login${`?${string}` | `#${string}` | ''}` | `/Login${`?${string}` | `#${string}` | ''}` | `${'/(Pages)'}${'/(Auth)'}/Signup${`?${string}` | `#${string}` | ''}` | `/Signup${`?${string}` | `#${string}` | ''}` | `${'/(Pages)'}${'/(SeparatePages)'}/MasterPassword${`?${string}` | `#${string}` | ''}` | `/MasterPassword${`?${string}` | `#${string}` | ''}` | `${'/(Pages)'}${'/(SeparatePages)'}/UpdatePass${`?${string}` | `#${string}` | ''}` | `/UpdatePass${`?${string}` | `#${string}` | ''}` | `${'/(Pages)'}${'/(SeparatePages)'}/Password${`?${string}` | `#${string}` | ''}` | `/Password${`?${string}` | `#${string}` | ''}` | `${'/(Pages)'}${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(Pages)'}${'/(tabs)'}/Settings${`?${string}` | `#${string}` | ''}` | `/Settings${`?${string}` | `#${string}` | ''}` | `${'/(Pages)'}${'/(tabs)'}/Vault${`?${string}` | `#${string}` | ''}` | `/Vault${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(Auth)'}/Login` | `/Login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(Auth)'}/Signup` | `/Signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(SeparatePages)'}/MasterPassword` | `/MasterPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(SeparatePages)'}/UpdatePass` | `/UpdatePass`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(SeparatePages)'}/Password` | `/Password`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(tabs)'}/Settings` | `/Settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(Pages)'}${'/(tabs)'}/Vault` | `/Vault`; params?: Router.UnknownInputParams; };
    }
  }
}
